[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_TURBOPACK = "false"
  NODE_VERSION = "22.18.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Configure secrets scanning
[secrets]
  scan = true
  scan_omit_paths = [".next/**/*", ".env*"]

# Exclude environment files from build
[build.ignore]
  files = [".env*", "*.local"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
