[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_USE_TURBOPACK = "false"
  NODE_VERSION = "22.18.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Configure secrets scanning
[secrets]
  scan = true
  scan_omit_paths = [
    ".next/**/*",
    "node_modules/**/*"
  ]

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
